baseurl = "/"
title = "Hugo Tanka Theme"
author = "Nan Xiao"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Chicken Scratch"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/evementen"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/chcknscrtch"
    weight = 3